### ISSUE TITLE
bq file removed from google-cloud-sdk

### ISSUE THREAD

**Issue by ysolis** [sudoforge/pkgbuilds#18]
I was working with Google Cloud SDK and i will begin to use BigQuery.

the `bq` cli command is removed from the AUR PKGBUILD. many *.py programs are removed ... but why `bq` ?

**Comment by sudoforge** [comment]
`bq` is not removed from the package:

```
➜ pacman -Fl google-cloud-sdk | grep 'bq$'
google-cloud-sdk opt/google-cloud-sdk/bin/bq
```

I imagine that you're looking at the `PKGBUILD` and seeing [this particular block][0], which _does_ look a little funky. What it's doing is creating symlinks for all executables from `src/opt/google-cloud-sdk/bin` to `/usr/bin`, and then removing a few of them (which is where you "see bq being removed").

Because `google-cloud-sdk.sh` updates the `PATH` variable (see [here][1]) to include `/opt/google-cloud-sdk/bin`, `bq` is still in your `PATH`.

I admit that this behavior is a bit odd, and isn't strictly necessary. The `PKGBUILD` could be refactored to remove this block altogether, and the package would still work as expected. This is something that should happen, but hasn't been a priority as it won't actually change the package in any meaningful way.

[0]: https://github.com/sudoforge/pkgbuilds/blob/master/google-cloud-sdk/PKGBUILD#L72-L76
[1]: https://github.com/sudoforge/pkgbuilds/blob/master/google-cloud-sdk/google-cloud-sdk.sh#L4
