### ISSUE TITLE
Unable to upgrade wee-slack-git to 2.5.0.r0.gf224e2f

### ISSUE THREAD

**Issue by Strykar** [sudoforge/pkgbuilds#28]
So no matter what I do, I cannot upgrade to `2.5.0.r0.gf224e2f`, I have tried using `aurutils`, deleting the cache/build dirs, downloading the `PKGBUILD` and using `makepkg`, it keeps building `wee-slack-git-2.6.0.r0.g4aac4bf-1` and tells me my version is up to date, asking me if I should reinstall.

Running latest updated Arch linux, how do I troubleshoot this?

**Comment by sudoforge** [comment]
The `wee-slack-git` package has a `pkgver()` function, which (like most `*-git` packages, by convention) is used by `makepkg` to calculate the `pkgver` at runtime (after fetching and unpacking the sources).

This is done because `*-git` packages build from `HEAD`, and therefore cannot pull a versioned artifact down from an upstream source. This means that any time you build the `wee-slack-git` package (cache notwithstanding), you will get the latest possible version of the package.

In the case of `wee-slack`, as of this comment, the `pkgver()` function evaluates to:

```
➜ git remote -v
origin  https://github.com/wee-slack/wee-slack.git (fetch)
origin  https://github.com/wee-slack/wee-slack.git (push)

➜ git log -1 --format='%H'
4aac4bff8cf8d37abe81c6c7b5b2c45399f86763

➜ git describe --long | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
2.6.0.r0.g4aac4bf
```

This means that any time you build the `wee-slack-git` package, you will build the `2.6.0.r0.g4aac4bf-${pkgrel}.tar.zst` archive. To wit, note that there has been a supplementary release of the `wee-slack-git` package and the `pkgrel` is now `2`.

**Comment by sudoforge** [comment]
If you would like to use an older release of `wee-slack` (your comment states that you're trying to build `2.5.0`), you have two options:

- Use the previous release of [the `wee-slack` package][0]. Note that this package builds versions based on upstream releases, and thus does not include incremental patches (which is the purpose of using `*-git` packages).
- Modify either of the `wee-slack` PKGBUILDs to fetch a particular SHA (this is probably a simpler edit in `//wee-slack/PKGBUILD`, actually) 
- Use the `2.5.0` revision of the `wee-slack` package and add in whatever patches you want/need.

**Comment by sudoforge** [comment]
Also, a little note that may be helpful, is that `*-git` packages (by convention and not by rule) are typically formatted as `<release>.r<count>.g<ref>`, where:

- `<release>` is the latest upstream release, a tag
- `<count>` is the number of commits between that tag and the current `HEAD` that is being built
- `<ref>` is the short format display of the commit being built (what `HEAD` is equivalent to)

**Comment by Strykar** [comment]
Thanks for clearing that up, so this is the only aur package having this issue, it seems -2 is detected but -1 is built:

```
aur sync wee-slack-git
==> Using [custom] repository
  -> wee-slack-git: (none) -> 2.6.0.r0.gf224e2f-2
==> Retrieving package files
From https://aur.archlinux.org/wee-slack-git
 = [up to date]      master     -> origin/master
Running makepkg --clean --syncdeps
==> Making package: wee-slack-git 2.6.0.r0.gf224e2f-2 (Thu 07 May 2020 05:22:27 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning wee-slack git repo...
Cloning into bare repository '/home/strykar/.cache/aurutils/sync/wee-slack-git/wee-slack'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 6092 (delta 59), reused 75 (delta 41), pack-reused 5991
Receiving objects: 100% (6092/6092), 2.81 MiB | 2.35 MiB/s, done.
Resolving deltas: 100% (3606/3606), done.
==> Validating source files with sha256sums...
    wee-slack ... Skipped
==> Extracting sources...
  -> Creating working copy of wee-slack git repo...
Cloning into 'wee-slack'...
done.
==> Starting pkgver()...
==> Updated version: wee-slack-git 2.6.0.r0.g4aac4bf-1
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "wee-slack-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: wee-slack-git 2.6.0.r0.g4aac4bf-1 (Thu 07 May 2020 05:22:34 PM IST)
==> Cleaning up...
==> Extracting custom.db.tar to a temporary location...
==> Extracting custom.files.tar to a temporary location...
==> Adding package 'wee-slack-git-2.6.0.r0.g4aac4bf-1-any.pkg.tar.xz'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file '/var/cache/pacman/custompkgs/custom.db.tar'
:: Synchronizing package databases...
 custom                                                                                  24.3 MiB   607 MiB/s 00:00 [#####################################################################] 100%
:: Synchronizing package databases...
 custom                                                                                 354.0 KiB   115 MiB/s 00:00 [#####################################################################] 100%
:: Starting full system upgrade...
 there is nothing to do
```

**Comment by sudoforge** [comment]
When the `pkgver()` function executes, it will reset the `pkgrel` if it changes the `pkgver`. This is expected.

**Comment by sudoforge** [comment]
I pushed a new commit (a6e0ec9cabc31a245bc294447b92923d58636165) to manually update the `pkgver` and `pkgrel`, which should avoid this confusion for you and other users, although it is not realistic to expect this regularly, as I (like most package maintainers) am not capable of following `HEAD` (which is why we use `pkgver()` to do this dynamically).

**Comment by Strykar** [comment]
@sudoforge I appreciate that, the reason that this git package came to my attention is that my Updates Available gnome notification triggers with this. I'll add it to ignore, thanks for clearing this up.

**Comment by sudoforge** [comment]
Not a problem, happy to help explain the intricacies of `*-git` packages!

I'm not sure what your "Updates Available" notification is doing, but in order to detect that you should rebuild `*-git` packages, you could simply track changes from the upstream project.

**Comment by Strykar** [comment]
It's checking using the built in tools Arch has, unfortunately, it cannot track upstream:
`/bin/sh -c "/usr/bin/checkupdates; /usr/bin/aur repo -d customrepo --list | /usr/bin/aur vercmp && /usr/bin/pacman -Qm | /usr/bin/aur vercmp"`

**Comment by sudoforge** [comment]
Well, since you're using `aurutils`, you could add `aur repo --list | aur vercmp-devel` to your script.

Unrelated question, why are you executing `pacman -Qm | aur vercmp`? `pacman -Qm` will list installed packages which are not found in sync databases -- in other words, packages which were installed manually and not from a repository (or packages which were installed, and then later removed from a repository).

You probably want something like:

```
/bin/sh -c "/usr/bin/checkupdates; /usr/bin/aur repo --list | /usr/bin/aur vercmp ; /usr/bin/aur repo --list | /usr/bin/aur vercmp-devel | uniq" 
```

**Comment by sudoforge** [comment]
Well, since you're using `aurutils`, you could add `aur repo --list | aur vercmp-devel` to your script.

Unrelated question, why are you executing `pacman -Qm | aur vercmp`? `pacman -Qm` will list installed packages which are not found in sync databases -- in other words, packages which were installed manually and not from a repository (or packages which were installed, and then later removed from a repository).

You probably want something like:

```
/bin/sh -c "/usr/bin/checkupdates; /usr/bin/aur repo --list | /usr/bin/aur vercmp ; /usr/bin/aur repo --list | /usr/bin/aur vercmp-devel | uniq" 
```
